create table if not exists public.pricing_feedback (
  id bigint generated by default as identity primary key,
  category text not null,
  currency text not null default 'NGN',
  suggested_amount numeric not null check (suggested_amount > 0),
  actual_amount numeric not null check (actual_amount > 0),
  outcome text not null check (outcome in ('accepted', 'negotiating', 'declined', 'not_sent')),
  adjustment_reason text not null check (adjustment_reason in ('scope_changed', 'client_budget', 'market_rate', 'personal_choice', 'none')),
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id text primary key,
  email text not null unique,
  name text not null,
  skill_work text,
  picture text,
  given_name text,
  family_name text,
  locale text,
  newsletter_consent boolean not null default false,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.users
  add column if not exists skill_work text;

alter table public.users
  add column if not exists newsletter_consent boolean not null default false;

create table if not exists public.user_estimates (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  result jsonb not null,
  source_description text not null,
  source_deliverables text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists user_estimates_user_created_at_idx
  on public.user_estimates (user_id, created_at desc);

-- Append-only analytics history. User history can be deleted without changing this count.
create table if not exists public.estimate_generation_events (
  id bigint generated by default as identity primary key,
  user_id text,
  source_estimate_id bigint unique,
  created_at timestamptz not null default now()
);

create index if not exists estimate_generation_events_created_at_idx
  on public.estimate_generation_events (created_at desc);

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('frontend', 'backend', 'database', 'gemini', 'feedback')),
  severity text not null default 'error' check (severity in ('info', 'warning', 'error', 'critical')),
  title text not null,
  message text not null,
  path text,
  created_at timestamptz not null default now()
);

create index if not exists admin_notifications_created_at_idx
  on public.admin_notifications (created_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  severity text not null default 'info' check (severity in ('system', 'feedback', 'info', 'warning', 'critical', 'error')),
  description text not null,
  entity text not null default 'System',
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

create index if not exists audit_logs_severity_idx
  on public.audit_logs (severity);

create table if not exists public.user_roles (
  user_id text primary key,
  role text not null check (role in ('Owner', 'Super Admin', 'Pricing Manager', 'Analyst', 'Standard User')),
  assigned_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.pricing_configurations (
  category text primary key,
  base_price numeric not null check (base_price > 0),
  minimum_price numeric not null check (minimum_price > 0),
  maximum_price numeric not null check (maximum_price > 0),
  updated_by text,
  updated_at timestamptz not null default now(),
  constraint check_min_base check (minimum_price <= base_price),
  constraint check_base_max check (base_price <= maximum_price)
);

-- Preserve estimates already saved before analytics events were introduced.
insert into public.estimate_generation_events (user_id, source_estimate_id, created_at)
select user_id, id, created_at
from public.user_estimates
on conflict (source_estimate_id) do nothing;

alter table public.pricing_feedback enable row level security;
revoke all on table public.pricing_feedback from anon, authenticated;
grant insert on table public.pricing_feedback to service_role;

alter table public.users enable row level security;
revoke all on table public.users from anon, authenticated;
grant insert, update, select on table public.users to service_role;

alter table public.user_estimates enable row level security;
revoke all on table public.user_estimates from anon, authenticated;
grant insert, select, delete on table public.user_estimates to service_role;

alter table public.estimate_generation_events enable row level security;
revoke all on table public.estimate_generation_events from anon, authenticated;
grant insert, select on table public.estimate_generation_events to service_role;

alter table public.admin_notifications enable row level security;
revoke all on table public.admin_notifications from anon, authenticated;
grant insert, select on table public.admin_notifications to service_role;

alter table public.audit_logs enable row level security;
revoke all on table public.audit_logs from anon, authenticated;
grant insert, select, delete on table public.audit_logs to service_role;

alter table public.user_roles enable row level security;
revoke all on table public.user_roles from anon, authenticated;
grant insert, update, select, delete on table public.user_roles to service_role;

alter table public.pricing_configurations enable row level security;
revoke all on table public.pricing_configurations from anon, authenticated;
grant insert, update, select, delete on table public.pricing_configurations to service_role;

