create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  email_type text not null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed', 'skipped')),
  provider_message_id text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint email_events_user_type_unique unique (user_id, email_type)
);

create index if not exists email_events_user_id_idx
  on public.email_events (user_id);

create index if not exists email_events_status_idx
  on public.email_events (status);

alter table public.email_events enable row level security;
revoke all on table public.email_events from anon, authenticated;
grant insert, select, update on table public.email_events to service_role;
